title: futon362's Page
header_pages: []
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# --- ここを修正 ---
baseurl: ""  # 空（ダブルクォーテーションのみ）にする
url: "https://futon362.github.io"
# ------------------

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji